### ISSUE TITLE
Minecraft Spawners

### ISSUE THREAD

**Issue by Redmagmafire** [partridge420x/Club-Lux-Gaming#1]
I had an Iron Pickaxe with silk touch on it and I broke two spawners, and I got nothing.

**To Reproduce**
1. Go to a cave
2. Take out your Iron Pickaxe with (specific enchants) Mending 1, Efficiency 5, and Silk touch 1.
3. Break the spawner(s) and you will get nothing.

**Expected behavior**
No spawners in inventory. It'll just say that u broke a spawner.

**Screenshots**
N/A but I got it on stream at https://www.youtube.com/watch?v=4_MrDn4kXyU at around 1 hour and 22 mins

**Comment by partridge420x** [comment]
Silk touch spawners is a members and up feature.

Join us here:  https://discord.gg/rBnnr6b

Link your minecraft account to your discord by typing ingame: /discord link

Ping our bot @DiscordSRV and message him the resulting 4 digit pin.

After that you've automatically become a member :D

**Comment by partridge420x** [comment]
Please dont be afraid to reply if you get stuck anywhere in the process

**Comment by partridge420x** [comment]
Issue was two fold. Needed to link
And i needed to update permissions as plugin dev changed permissions nodes again...
