### ISSUE TITLE
[Minecraft server Suggestion]

### ISSUE THREAD

**Issue by Zonzo2** [partridge420x/Club-Lux-Gaming#4]
**Is your feature request related to a problem? If so Please describe.**
A clear and concise description of what the suggestion would be, How it would possibly be implemented. How it would be balanced into our current server. 
Guilds. Or towns. Top guild/town of the week gets a price. 
Quests, would help increase interest. esp if quests HELP NEW PLAYERS out. 
Custom Mobs
MAKE IT WHERE PEOPLE CANT SEE WHERE CUSTOM SPAWNERS ARE PLACED PLS. 
allow ability to edit all flags in our claim area (like firespread)

**Describe alternatives you've considered**

**Additional context**

**Comment by partridge420x** [comment]
- Spawners no longer have holograms.

- Guilds/teams may be implemented in the future, as of current i cant find a way to add it with our current means of player protection

- Most custom mobs plugins either take alot of time, or money to buy premade plugins. If you'd like to Upgrade your patreon to a more current tier. It would help out with things like this

- Quests were a wanted feature. I am focusing on things higher in my priority list such as stable bedrock player connectivity. And fixing the incompatibility with our offline authentication and bedrock connectivity plugins
